const {chromium}=require(process.env.YAVCHN_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width===1440?900:844});await page.goto('http://localhost:8080/static/mockups/reader.html');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const reader=page.locator('.reader.active');await reader.getByRole('button',{name:'Discussion',exact:false}).first().click();assert.equal(await reader.locator('.panes').getAttribute('data-mode'),'discussion');await reader.getByRole('button',{name:'Split',exact:true}).click();await reader.getByRole('separator').focus();await page.keyboard.press('ArrowUp');assert.equal(await reader.getByRole('separator').getAttribute('aria-valuenow'),'50');await reader.getByRole('button',{name:'Article',exact:true}).click();await page.getByRole('button',{name:'Show story list',exact:true}).click();assert.equal(await page.locator('.taskbar').isVisible(),true);await page.locator('.task').nth(1).click();assert.equal(await page.locator('.reader.active').getAttribute('data-reader'),'1');await page.locator('.task').nth(0).click();await page.screenshot({path:process.env.TEMP+'/yavchn-mockup-'+width+'.png'});await page.getByRole('button',{name:'Site menu',exact:true}).click();await page.locator('.menu-items').getByRole('button',{name:'Window ›',exact:true}).click();await page.locator('.menu-items').getByRole('button',{name:/Git 3/}).click();assert.equal(await page.locator('.reader.active').getAttribute('data-reader'),'1');}await page.goto('http://localhost:8080/static/mockups/');
await page.locator('.preview-app .reader.active').waitFor();
for(const label of ['Small phone','Phone','Tablet','Desktop']){
 await page.getByRole('button',{name:label,exact:true}).click();
 await page.locator('.reader.active').getByRole('button',{name:'Discussion',exact:false}).first().click();
 assert.equal(await page.locator('.reader.active .panes').getAttribute('data-mode'),'discussion');
 await page.locator('.reader.active').getByRole('button',{name:'Article',exact:true}).click();
}
await page.screenshot({path:process.env.TEMP+'/yavchn-mockup-wrapper.png'});
assert.deepEqual(errors,[]);console.log('Mockup layouts and controls passed at 320, 390, 768 and 1440 pixels.')}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
