const assert = require('node:assert/strict');
const { chromium } = require(process.env.YAVCHN_PLAYWRIGHT || 'playwright');

(async function () {
  const browser = await chromium.launch({ channel: process.env.YAVCHN_BROWSER_CHANNEL || 'msedge', headless: true });
  try {
    await require('./viewport.browser.cjs')(browser, process.argv[2]);
    const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
    page.setDefaultTimeout(8000);
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', msg => { if (msg.type() === 'warning' && msg.text().includes('pudl-menubar')) errors.push(msg.text()); });
    await page.route('**/api/article?*', route => route.fulfill({ contentType: 'text/html', body: '<article style="height:3000px">Article fixture</article>' }));
    await page.route('**/api/discussion?*', route => route.fulfill({ contentType: 'text/html', body: '<div class="discussion-content" style="height:3000px">Discussion fixture</div>' }));
    await page.goto(process.argv[2] + '/hn/');
    await page.waitForFunction(() => window.yavchn.readers && window.pudlWindows);
    // PUDL makes both menu titles and hamburger buttons toggle closed.
    const toggleMenu = async (control, touch) => {
      for (const expanded of ['true', 'false', 'true', 'false']) {
        if (touch) await control.tap(); else await control.click();
        await control.page().waitForFunction(([el, value]) => el.getAttribute('aria-expanded') === value, [await control.elementHandle(), expanded]);
      }
    };
    await toggleMenu(page.locator('.menubar-menu:not(.menubar-one) > button.menubar-glyph').first(), false);
    await toggleMenu(page.getByRole('menuitem', { name: 'View', exact: true }), false);
    const touchContext = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true });
    const touchPage = await touchContext.newPage();
    await touchPage.goto(process.argv[2] + '/hn/');
    await touchPage.locator('.menubar-one > button').waitFor();
    await toggleMenu(touchPage.locator('.menubar-one > button'), true);
    await touchPage.locator('.menubar-one > button').tap();
    await touchPage.getByRole('menuitem', { name: 'Feed', exact: true }).tap();
    await touchPage.getByRole('menuitem', { name: 'Hacker News', exact: true }).waitFor();
    await touchPage.getByRole('menuitem', { name: /Back/ }).tap();
    await touchContext.close();
    const story = (key, article) => page.waitForFunction(([k, a]) => document.querySelector(`.win[data-win="${k}"] .story`)?.dataset.storyKey === a, [key, article]);
    const siteBadge = async (key, source, label) => {
      await page.waitForFunction(([k, s]) => document.querySelector(`[data-win-tab="${k}"]`)?.getAttribute('data-reader-source') === s, [key, source]);
      assert.equal(await page.locator(`[data-win="${key}"] .win-head .reader-site .visually-hidden`).count(), 1);
      assert.equal((await page.locator(`[data-win="${key}"] .win-head .reader-site`).textContent()).trim(), label);
      assert.equal((await page.locator(`[data-win-tab="${key}"] .reader-site`).innerText()).trim(), label);
      await page.waitForFunction(k => [...document.querySelectorAll(`[data-win="${k}"] .reader-site img, [data-win-tab="${k}"] .reader-site img`)].every(img => img.complete && img.naturalWidth > 0), key);
    };
    await page.waitForFunction(() => [...document.querySelectorAll('.source-seg .source-icon')].filter(img => img.complete && img.naturalWidth > 0).length === 2);
    assert.equal(await page.locator('.source-seg [data-source="pinned"] .source-glyph-pin').count(), 1);
    assert.equal(await page.locator('.source-seg [data-source="find"] .source-glyph-find').count(), 1);
    const clickRow = async id => page.locator(`#row-hn-${id} > a.md-item`).click();
    const refreshFeed = async () => {
      const before = page.url();
      await page.evaluate(() => {
        window.feedRefreshCheck = {
          list: document.querySelector('.story-list'),
          reader: document.querySelector('.win.active .story'),
          history: history.length
        };
      });
      const requested = page.waitForRequest(req => req.headers()['cache-control'] === 'no-cache' && req.url() === before);
      await page.getByRole('menuitem', { name: 'Feed', exact: true }).click();
      await page.getByRole('menuitem', { name: 'Refresh the feed', exact: true }).click();
      await requested;
      await page.waitForFunction(() => document.querySelector('.feed-refresh-status')?.textContent === 'Feed refreshed.');
      assert.equal(page.url(), before);
      assert.equal(await page.evaluate(() => window.feedRefreshCheck.list !== document.querySelector('.story-list') && window.feedRefreshCheck.reader === document.querySelector('.win.active .story') && window.feedRefreshCheck.history === history.length), true);
      // A failed refresh must keep the list and readers usable without navigation.
      await page.route(before, route => route.fulfill({ status: 503, contentType: 'text/html', body: 'Unavailable' }));
      await page.evaluate(() => { window.feedRefreshCheck.list = document.querySelector('.story-list'); });
      await page.locator('#feed-refresh').click();
      await page.getByText('The feed could not be refreshed. Try again.', { exact: true }).waitFor();
      assert.equal(await page.locator('#feed-refresh').isEnabled(), true);
      assert.equal(await page.evaluate(() => window.feedRefreshCheck.list === document.querySelector('.story-list') && window.feedRefreshCheck.reader === document.querySelector('.win.active .story')), true);
      await page.unroute(before);
    };
    await clickRow('1');
    await story('reader-1', 'hn-1');
    await siteBadge('reader-1', 'hn', 'HN');
    const siteTitles = () => page.locator('.menubar-menu:not(.menubar-front):not(.menubar-one) .menubar-title').allTextContents();
    assert.deepEqual((await siteTitles()).map(t => t.trim()), ['YAVCHN', 'Go', 'Applets', 'Feed', 'View', 'Window', 'Help']);
    await page.locator('.menubar-title').filter({ hasText: /^Reader$/ }).click();
    await page.getByRole('menuitem', { name: 'Copy story link', exact: true }).waitFor();
    await page.getByRole('menuitem', { name: 'Close window', exact: true }).waitFor();
    assert.equal(await page.getByRole('menuitemcheckbox', { name: 'Pin this story', exact: true }).count(), 0);
    await page.keyboard.press('Escape');
    await page.getByRole('menuitem', { name: 'Go', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Next story', exact: true }).waitFor();
    assert.match(await page.locator('.menubar-panel:popover-open').innerText(), /Reader/i);
    await page.keyboard.press('Escape');
    await page.getByRole('menuitem', { name: 'Feed', exact: true }).click();
    await page.getByRole('menuitem', { name: 'View', exact: true }).hover();
    await page.getByRole('menuitem', { name: 'View', exact: true }).click();
    assert.equal(await page.locator('.menubar-panel:popover-open').count(), 0);
    await refreshFeed();
    await page.evaluate(() => window.pudlWindows.dock('reader-1', 'left'));
    await clickRow('2');
    await story('reader-2', 'hn-2');
    await story('reader-1', 'hn-1');
    // An open menu must not silently switch its target to another reader.
    await page.getByRole('menuitem', { name: 'Story', exact: true }).click();
    await page.evaluate(() => window.pudlWindows.raise('reader-1'));
    await page.waitForFunction(() => !document.querySelector('.menubar-panel:popover-open'));
    await page.locator('.menubar-title').filter({ hasText: /^Reader$/ }).click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.story-row [data-reader-new]').count(), 0);
    await page.getByRole('menuitem', { name: 'Story', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Open in new reader window', exact: true }).click();
    await story('reader-3', 'hn-1');
    await page.evaluate(() => window.pudlWindows.minimize('reader-3'));
    await siteBadge('reader-3', 'hn', 'HN');
    await clickRow('1');
    await story('reader-2', 'hn-1');
    await story('reader-3', 'hn-1');
    await page.evaluate(() => window.pudlWindows.raise('reader-1'));
    await clickRow('2');
    await story('reader-2', 'hn-2');
    await story('reader-1', 'hn-1');
    await page.evaluate(() => window.yavchn.nextStory(document.querySelector('[data-win="reader-1"]')).click());
    await story('reader-1', 'hn-2');
    await page.goBack();
    await story('reader-1', 'hn-1');
    await page.goForward();
    await story('reader-1', 'hn-2');
    await page.reload();
    await story('reader-1', 'hn-2');
    await story('reader-2', 'hn-2');
    assert.equal(await page.locator('[data-win="reader-1"]').getAttribute('data-win-mode'), 'dock-left');
    await page.getByRole('menuitem', { name: 'Window', exact: true }).click();
    await page.getByRole('menuitem', { name: 'New reader window', exact: true }).click();
    await page.locator('[data-win="reader-4"]').waitFor();
    assert.match(await page.locator('[data-win="reader-4"]').innerText(), /Select an article/);
    assert.equal(await page.locator('[data-win="reader-4"] .reader-site, [data-win-tab="reader-4"] .reader-site').count(), 0);
    await clickRow('1');
    await story('reader-4', 'hn-1');
    await siteBadge('reader-4', 'hn', 'HN');
    await page.goBack();
    await page.waitForFunction(() => !document.querySelector('[data-win="reader-4"] .story')?.dataset.storyKey);
    assert.equal(await page.locator('[data-win="reader-4"] .reader-site, [data-win-tab="reader-4"] .reader-site').count(), 0);
    await page.goForward();
    await story('reader-4', 'hn-1');
    await page.evaluate(() => window.pudlWindows.close('reader-4'));
    assert.equal(new URL(page.url()).searchParams.has('r.reader-4'), false);
    // A list navigation carries the reader assignments through region swaps.
    await page.locator('a[href="/pinned/"]').first().evaluate(a => a.click());
    await page.waitForURL('**/pinned/**');
    assert.equal(new URL(page.url()).searchParams.get('r.reader-1'), 'hn-2');
    await page.reload();
    await story('reader-1', 'hn-2');
    // Ordinary browsing keeps one reader per source, even across list swaps.
    await page.goto(process.argv[2] + '/hn/');
    await clickRow('1');
    await story('reader-1', 'hn-1');
    await page.locator('a[data-source="lobsters"]').click();
    await page.locator('#row-lobsters-1 > a.md-item').click();
    await story('reader-2', 'lobsters-1');
    await siteBadge('reader-2', 'lobsters', 'Lobsters');
    await refreshFeed();
    if (process.env.YAVCHN_SCREENSHOT) await page.screenshot({ path: process.env.YAVCHN_SCREENSHOT });
    await story('reader-1', 'hn-1');
    await page.locator('a[data-source="hn"]').click();
    await clickRow('2');
    await story('reader-1', 'hn-2');
    await story('reader-2', 'lobsters-1');
    await page.getByRole('menuitem', { name: 'Window', exact: true }).click();
    await page.getByRole('menuitem', { name: 'New reader window', exact: true }).click();
    await page.locator('[data-win="reader-3"]').waitFor();
    await page.locator('a[data-source="lobsters"]').click();
    await page.locator('#row-lobsters-2 > a.md-item').click();
    await story('reader-3', 'lobsters-2');
    await siteBadge('reader-3', 'lobsters', 'Lobsters');
    await story('reader-2', 'lobsters-1');
    await page.locator('a[data-source="hn"]').click();
    await clickRow('1');
    await story('reader-1', 'hn-1');
    await story('reader-3', 'lobsters-2');
    // Explicit reader navigation updates its source marker and browser history.
    await page.evaluate(() => window.yavchn.readers.read('lobsters-1', null, document.querySelector('[data-win="reader-1"]')));
    await story('reader-1', 'lobsters-1');
    await siteBadge('reader-1', 'lobsters', 'Lobsters');
    await page.goBack();
    await story('reader-1', 'hn-1');
    await siteBadge('reader-1', 'hn', 'HN');
    // Two views of one article retain separate reading positions on reload.
    await page.goto(process.argv[2] + '/hn/?open=reader-1,reader-2&r.reader-1=hn-1&r.reader-2=hn-1');
    await page.waitForFunction(() => document.querySelectorAll('.discussion-content').length === 2);
    await page.evaluate(() => {
      document.querySelectorAll('[data-reader-pane="split"]').forEach(b => b.click());
      document.querySelector('[data-win="reader-1"] .story-discussion-body').scrollTop = 150;
      document.querySelector('[data-win="reader-2"] .story-discussion-body').scrollTop = 450;
    });
    await page.waitForFunction(() => {
      const s = JSON.parse(localStorage.getItem('yavchn-applet-state'));
      return s['reader-1:hn-1']?.s.includes('d=150') && s['reader-2:hn-1']?.s.includes('d=450');
    });
    await page.reload();
    await page.waitForFunction(() => document.querySelector('[data-win="reader-1"] .story-discussion-body')?.scrollTop === 150 && document.querySelector('[data-win="reader-2"] .story-discussion-body')?.scrollTop === 450);
    // Pane selection belongs to a reader and preserves both scroll positions.
    await page.evaluate(() => {
      const r = document.querySelector('[data-win="reader-1"]');
      r.querySelector('[data-reader-pane="article"]').click();
    });
    assert.equal(await page.locator('[data-win="reader-1"] .story-discussion').isVisible(), false);
    assert.equal(await page.locator('[data-win="reader-2"] .story').getAttribute('data-reader-pane'), 'split');
    const shared = await page.evaluate(() => window.pudlWindows.shareURL('reader-1'));
    assert.equal(new URL(shared).searchParams.get('pane'), 'article');
    await page.evaluate(() => document.querySelector('[data-win="reader-1"] [data-reader-pane="split"]').click());
    assert.equal(await page.locator('[data-win="reader-1"] .story-discussion-body').evaluate(el => el.scrollTop), 150);
    // The pane chosen last opens every story that has no place of its own,
    // in a new window, in a window that moves to another story, and on a page.
    await page.evaluate(() => document.querySelector('[data-win="reader-1"] [data-reader-pane="discussion"]').click());
    await page.goto(process.argv[2] + '/hn/?open=reader-3&r.reader-3=hn-2');
    await page.waitForFunction(() => document.querySelector('[data-win="reader-3"] .story[data-story-key="hn-2"]')?.dataset.readerPane === 'discussion');
    await page.evaluate(() => document.querySelector('[data-win="reader-3"] [data-reader-pane="article"]').click());
    await clickRow('1');
    await story('reader-3', 'hn-1');
    assert.equal(await page.locator('[data-win="reader-3"] .story').getAttribute('data-reader-pane'), 'article');
    await page.evaluate(() => document.querySelector('[data-win="reader-3"] [data-reader-pane="split"]').click());
    await page.goto(process.argv[2] + '/story/hn/2?view=classic');
    await page.waitForFunction(() => document.querySelector('.story[data-story-key="hn-2"]')?.dataset.readerPane === 'split');
    await page.goto(process.argv[2] + '/hn/?view=window');
    await page.goto(process.argv[2] + '/hn/?open=reader-1,reader-2&r.reader-1=hn-1&r.reader-2=hn-1');
    await page.waitForFunction(() => document.querySelectorAll('.discussion-content').length === 2);
    await page.locator('.sidebar-toggle').click();
    assert.equal(await page.locator('.story-list').isVisible(), false);
    assert.equal(await page.locator('.sidebar-toggle').getAttribute('aria-expanded'), 'false');
    const divider = page.locator('.md-resize');
    assert.equal(await divider.isVisible(), true);
    assert.equal(await page.locator('.md-sidebar').evaluate(el => el.inert), true);
    assert.equal((await divider.boundingBox()).width, 24);
    await divider.focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('.story-list').isVisible(), true);
    await divider.focus();
    await page.keyboard.press('Home');
    assert.equal(await page.locator('.story-list').isVisible(), false);
    await page.locator('.sidebar-toggle').click();
    assert.equal(await page.locator('.story-list').isVisible(), true);
    await page.setViewportSize({ width: 600, height: 900 });
    await page.locator('.source-switch .menu-btn').click();
    assert.match(await page.locator('.source-switch .menu-btn-label').evaluate(el => getComputedStyle(el, '::before').backgroundImage), /hn-favicon/);
    assert.match(await page.locator('.source-switch .seg-choice[href="/lobsters/"]').evaluate(el => getComputedStyle(el, '::before').backgroundImage), /lobsters-favicon/);
    // The narrow policy preserves URL placement and the mounted reader.
    await page.waitForFunction(() => window.pudlWindows.effectivePlacement('reader-1').mode === 'maximized');
    const requestedPlacement = await page.evaluate(() => JSON.stringify(window.pudlWindows.state().place['reader-1']));
    const policyURL = page.url();
    await page.evaluate(() => { window.policyReader = document.querySelector('[data-win="reader-1"] .story'); });
    assert.equal(await page.evaluate(() => window.pudlWindows.menuCommands('reader-1').find(c => c.label === 'Restore to floating')?.disabled), true);
    await page.evaluate(() => window.pudlWindows.dock('reader-1', 'left'));
    assert.equal(page.url(), policyURL);
    await page.setViewportSize({ width: 1500, height: 1000 });
    await page.waitForFunction(() => !document.querySelector('[data-win="reader-1"]').hasAttribute('data-win-restricted'));
    assert.equal(await page.evaluate(() => JSON.stringify(window.pudlWindows.state().place['reader-1'])), requestedPlacement);
    assert.equal(await page.evaluate(() => window.policyReader === document.querySelector('[data-win="reader-1"] .story')), true);
    assert.equal(page.url(), policyURL);
    // Returning to the feed on mobile minimizes readers. Each source must
    // restore its own instance across repeated selections and source switches.
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(process.argv[2] + '/hn/');
    await clickRow('1');
    await story('reader-1', 'hn-1');
    await page.locator('.md-resize').focus();
    await page.keyboard.press('End');
    assert.equal(await page.locator('.story-list').isVisible(), true);
    await page.locator('.sidebar-toggle').click();
    assert.equal(await page.locator('.story-list').isVisible(), false);
    await story('reader-1', 'hn-1');
    await page.locator('.sidebar-toggle').click();
    assert.equal(await page.locator('.win-bar').isVisible(), true);
    assert.equal(await page.locator('.md-detail .win-bar').count(), 0);
    const taskBox = await page.locator('.win-bar').boundingBox();
    assert.ok(taskBox.width >= 380 && taskBox.y + taskBox.height <= 845);
    await clickRow('2');
    await story('reader-1', 'hn-2');
    assert.equal(await page.locator('.win.story-win').count(), 1);
    const mobileSource = async source => {
      await page.locator('.source-switch .menu-btn').click();
      await page.locator(`.source-switch .seg-choice[href="/${source}/"]`).click();
      await page.waitForURL(`**/${source}/**`);
    };
    await page.locator('.sidebar-toggle').click();
    await mobileSource('lobsters');
    await page.locator('#row-lobsters-1 > a.md-item').click();
    await story('reader-2', 'lobsters-1');
    await page.locator('.sidebar-toggle').click();
    await page.locator('#row-lobsters-2 > a.md-item').click();
    await story('reader-2', 'lobsters-2');
    await page.locator('.sidebar-toggle').click();
    await mobileSource('hn');
    await clickRow('1');
    await story('reader-1', 'hn-1');
    await page.locator('.sidebar-toggle').click();
    await page.reload();
    await clickRow('2');
    await story('reader-1', 'hn-2');
    assert.equal(await page.locator('.win.story-win').count(), 2);
    await story('reader-2', 'lobsters-2');
    // Choosing a source while reading, on a phone, shows that source's list,
    // whether it is another source or the one already shown.
    assert.equal(await page.locator('.story-list').isVisible(), false);
    await mobileSource('lobsters');
    await page.locator('#row-lobsters-1').waitFor();
    await page.waitForFunction(() => document.querySelector('.story-list').checkVisibility());
    await page.locator('#row-lobsters-2 > a.md-item').click();
    await story('reader-2', 'lobsters-2');
    await mobileSource('hn');
    await page.locator('#row-hn-1').waitFor();
    await page.waitForFunction(() => document.querySelector('.story-list').checkVisibility());
    await clickRow('2');
    await story('reader-1', 'hn-2');
    assert.equal(await page.locator('.story-list').isVisible(), false);
    await page.locator('.source-switch .menu-btn').click();
    await page.locator('.source-switch .seg-choice[aria-current="page"]').click();
    await page.waitForFunction(() => document.querySelector('.story-list').checkVisibility());
    assert.equal(new URL(page.url()).pathname, '/hn/');
    await clickRow('2');
    await story('reader-1', 'hn-2');
    // The same minimized-reader reuse applies after widening the viewport.
    await page.locator('.sidebar-toggle').click();
    await page.setViewportSize({ width: 1500, height: 1000 });
    await clickRow('1');
    await story('reader-1', 'hn-1');
    assert.equal(await page.locator('.win.story-win').count(), 2);
    // The View menu chooses the browsing view, shares the saved preference
    // and preserves the article; with script the bar has no selector of its own.
    const viewMenu = async label => {
      await page.getByRole('menuitem', { name: 'View', exact: true }).click();
      await page.getByRole('menuitemcheckbox', { name: label, exact: true }).click();
    };
    assert.equal(await page.locator('.topbar .view-seg').count(), 0);
    await viewMenu('Classic');
    await page.waitForURL('**/story/hn/1');
    assert.equal(await page.locator('body').getAttribute('data-view'), 'classic');
    assert.equal(await page.locator('[data-win-layer], [data-focus-toggle]').count(), 0);
    assert.equal(await page.getByRole('menuitem', { name: 'Feed', exact: true }).count(), 0);
    await page.locator('.menubar-title').filter({ hasText: /^Story$/ }).click();
    assert.equal(await page.getByRole('menuitem', { name: 'Next story', exact: true }).count(), 0);
    await page.keyboard.press('Escape');
    const focusPreference = await page.evaluate(() => localStorage.getItem('yavchn-focus'));
    await page.keyboard.press('f');
    assert.equal(await page.evaluate(() => localStorage.getItem('yavchn-focus')), focusPreference);
    await page.getByRole('link', { name: 'Stories', exact: true }).click();
    await page.waitForURL('**/hn/?view=classic');
    const listBox = await page.locator('.md-sidebar').boundingBox();
    assert.ok(listBox.width > 1400, 'Classic feed should use the full page');
    await clickRow('2');
    await page.waitForURL('**/story/hn/2');
    await viewMenu('Windowed');
    await page.waitForFunction(() => !!document.querySelector('[data-win-layer]'));
    assert.equal((await page.context().cookies()).find(c => c.name === 'yavchn-view').value, 'window');
    await page.getByRole('menuitem', { name: 'View', exact: true }).click();
    await page.getByRole('menuitemcheckbox', { name: 'Windowed', exact: true }).click();
    await page.waitForLoadState('load');
    await page.waitForFunction(() => !!window.pudlWindows);
    assert.equal((await page.context().cookies()).find(c => c.name === 'yavchn-view').value, 'window');
    await page.goto(process.argv[2] + '/hn/');
    assert.equal(await page.locator('body').getAttribute('data-view'), 'window');
    await page.goto(process.argv[2] + '/story/hn/1');
    assert.equal(await page.locator('body').getAttribute('data-view'), 'classic');
    await page.getByRole('menuitem', { name: 'Applets', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Look up a user…', exact: true }).click();
    await page.waitForURL('**/user');
    assert.equal(await page.locator('body').getAttribute('data-view'), 'classic');
    assert.equal(await page.locator('[data-win-layer], [data-focus-toggle]').count(), 0);
    await page.getByRole('menuitem', { name: 'View', exact: true }).click();
    await page.getByRole('menuitemcheckbox', { name: 'Windowed', exact: true }).click();
    await page.locator('.win[data-win="user"]').waitFor();
    assert.deepEqual(errors, []);
    const nojs = await browser.newContext({ javaScriptEnabled: false });
    const plain = await nojs.newPage();
    await plain.goto(process.argv[2] + '/hn/?open=reader-1&r.reader-1=hn-1');
    assert.equal(await plain.locator('.story-row [data-reader-new]').count(), 0);
    await plain.getByRole('link', { name: 'New reader window', exact: true }).click();
    assert.equal(await plain.locator('.win').count(), 2);
    await plain.goto(process.argv[2] + '/hn/?view=classic');
    await plain.locator('.view-seg').getByRole('button', { name: 'Classic', exact: true }).click();
    await plain.waitForURL('**/hn/?view=classic');
    assert.equal((await nojs.cookies()).find(c => c.name === 'yavchn-view').value, 'classic');
    await plain.locator('#row-hn-1 > a.md-item').click();
    await plain.waitForURL('**/story/hn/1');
    assert.equal(await plain.locator('[data-win-layer], [data-focus-toggle]').count(), 0);
    await plain.goto(process.argv[2] + '/settings');
    await plain.locator('.settings-view-form button[value=window]').click();
    await plain.waitForURL('**/settings');
    assert.equal((await nojs.cookies()).find(c => c.name === 'yavchn-view').value, 'window');
    await page.goto(process.argv[2] + '/hn/?view=window');
    await page.locator('.menubar-title').filter({ hasText: /YAVCHN/ }).click();
    await page.getByRole('menuitem', { name: 'Settings', exact: true }).click();
    const settings = page.locator('.win[data-win="settings"] [data-settings]');
    await settings.waitFor();
    assert.equal(await settings.locator('select').count(), 0);
    // Like every window, Settings has its identity menu, also when the
    // window comes from the address as the page loads.
    await page.goto(new URL('?view=window&open=settings&top=settings', page.url()).href);
    await page.locator('.win[data-win="settings"] [data-settings]').waitFor();
    await page.locator('.menubar-front .menubar-title').filter({ hasText: /^Settings$/ }).click();
    for (const name of ['Open as a page', 'Copy settings link', 'Close window']) {
      await page.getByRole('menuitem', { name, exact: true }).waitFor();
    }
    await page.keyboard.press('Escape');
    const settingsWindow = page.locator('.win[data-win="settings"]');
    assert.equal(await settingsWindow.getAttribute('data-win-size'), 'content');
    await page.getByRole('menuitem', { name: 'Window', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Reset position', exact: true }).waitFor();
    assert.equal(await page.getByRole('menuitem', { name: 'Maximize', exact: true }).count(), 0);
    assert.equal(await page.getByRole('menuitem', { name: 'Dock at the bottom', exact: true }).count(), 0);
    await page.getByRole('menuitem', { name: 'Close all windows', exact: true }).waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await settingsWindow.locator('[data-win-action="maximize"]').isVisible(), false);
    await settingsWindow.locator('.win-title').dblclick();
    assert.equal(await settingsWindow.getAttribute('data-win-mode'), 'floating');
    await settings.locator('[data-setting="theme"][value="light"]').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
    await settings.locator('[data-setting="sort"][value="newest"]').click();
    assert.equal(await page.evaluate(() => window.yavchn.sort.get()), 'newest');
    await page.evaluate(() => window.yavchn.sort.set('oldest'));
    assert.equal(await settings.locator('[data-setting="sort"][aria-pressed="true"]').getAttribute('value'), 'oldest');
    await settings.locator('.filters-add input').fill('https://www.a.example/path');
    await settings.getByRole('button', { name: 'Block', exact: true }).click();
    assert.equal(await page.locator('#row-hn-1').evaluate(el => el.classList.contains('filtered')), true);
    assert.equal(await page.locator('#filters-dialog .filters-list-remove[data-domain="a.example"]').count(), 1);
    await settings.getByRole('button', { name: 'Unblock a.example', exact: true }).click();
    assert.equal(await page.locator('#row-hn-1').evaluate(el => el.classList.contains('filtered')), false);
    assert.equal(await settings.locator('button[name="placement"][aria-pressed="true"]').getAttribute('value'), 'floating');
    const oldPlacement = await page.evaluate(() => JSON.stringify(window.pudlWindows.state().place));
    await settings.locator('button[name="placement"][value="maximized"]').click();
    await settings.getByText('Article window preference saved.', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => JSON.stringify(window.pudlWindows.state().place)), oldPlacement);
    await page.evaluate(() => window.yavchn.readers.create('hn-1'));
    await page.waitForFunction(() => window.pudlWindows.state().place[window.pudlWindows.state().top]?.mode === 'maximized');
    await page.evaluate(() => { window.pudlWindows.close(window.pudlWindows.state().top); window.pudlWindows.raise('settings'); });
    await settings.locator('button[name="placement"][value="floating"]').click();
    await page.waitForFunction(() => document.querySelector('.settings-placement-form button[value="floating"]').getAttribute('aria-pressed') === 'true');
    const workspace = page.url();
    await settings.locator('.settings-view-form button[value="classic"]').click();
    await settings.getByText('Default view saved.', { exact: true }).waitFor();
    assert.equal(page.url(), workspace);
    assert.equal((await page.context().cookies()).find(c => c.name === 'yavchn-view').value, 'classic');
    await page.route('**/settings/view', route => route.fulfill({ status: 503, body: 'Unavailable' }));
    await settings.locator('.settings-view-form button[value="window"]').click();
    await settings.getByText('The default view could not be saved. Try again.', { exact: true }).waitFor();
    assert.equal(await settings.locator('.settings-view-form button[aria-pressed="true"]').getAttribute('value'), 'classic');
    await page.unroute('**/settings/view');
    await page.goto(process.argv[2] + '/hn/');
    assert.equal(await page.locator('body').getAttribute('data-view'), 'classic');
    await page.locator('.menubar-title').filter({ hasText: /YAVCHN/ }).click();
    await page.getByRole('menuitem', { name: 'Settings', exact: true }).click();
    await page.waitForURL('**/settings');
    assert.equal(await page.locator('[data-win-layer]').count(), 0);
    assert.equal(await page.locator('[data-setting="theme"][aria-pressed="true"]').getAttribute('value'), 'light');
    assert.equal(await page.locator('[data-setting="sort"][aria-pressed="true"]').getAttribute('value'), 'oldest');
    assert.equal(await page.locator('.settings-view-form button[aria-pressed="true"]').getAttribute('value'), 'classic');
    assert.deepEqual(errors, []);
    await page.goto(process.argv[2] + '/hn/?view=window&open=replies&top=replies');
    await page.locator('.menubar-title').filter({ hasText: /^Watch$/ }).click();
    await page.getByRole('menuitem', { name: 'Watch another user…', exact: true }).waitFor();
    await page.keyboard.press('Escape');
    await page.locator('.menubar-title').filter({ hasText: /^Replies$/ }).click();
    await page.getByRole('menuitem', { name: 'Copy replies link', exact: true }).waitFor();
    await page.getByRole('menuitem', { name: 'Close window', exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('.win[data-win="replies"]'));
    assert.equal(await page.locator('.menubar-front').count(), 0);
    // Help opens the privacy policy as a window, and the About box's link
    // to the terms closes the box so the window it opens is in view.
    await page.getByRole('menuitem', { name: 'Help', exact: true }).click();
    await page.getByRole('menuitem', { name: 'Privacy policy', exact: true }).click();
    await page.locator('.win[data-win="privacy"] .legal h2').first().waitFor();
    await page.locator('.menubar-front .menubar-title').filter({ hasText: /^Privacy policy$/ }).click();
    await page.getByRole('menuitem', { name: 'Copy privacy policy link', exact: true }).waitFor();
    await page.keyboard.press('Escape');
    await page.locator('.menubar-title').filter({ hasText: /^\s*YAVCHN\s*$/ }).click();
    await page.getByRole('menuitem', { name: 'About YAVCHN', exact: true }).click();
    await page.locator('#about-dialog').getByRole('link', { name: 'Terms of use', exact: true }).click();
    await page.locator('.win[data-win="terms"] .legal').waitFor();
    assert.equal(await page.locator('#about-dialog').evaluate(d => d.open), false);
    assert.ok(new URL(page.url()).searchParams.get('open').split(',').includes('terms'));
    assert.deepEqual(errors, []);
    await nojs.close();
    console.log('Reader creation, per-site reuse, docking, minimization, duplicates, independent scroll positions, history, reload, list navigation and no-JS links passed.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
